### ISSUE TITLE
Mega Issue for Transit Info

### ISSUE THREAD

**Issue by AGiersch1804** [uWaterloo/OpenData#93] opened 2014-01-14 01:13 UTC
I would like to see info on busses such as:
- Bus stop locations
- Bus names
- Bus departure times

For all busses, GRT, GO Bus, UoW Shuttle, FedsBus

IF POSSIBLE:
- Bus routes

**Comment by nathanv** [comment] 2015-07-17 14:26
Good morning!
@mrandrewandrade: I am closing #123 because it is a duplicate of this Issue. as per your comment on #123: Definitely this is something that we'd love to add. Aside from the GRT, Fedbus, Shuttles, etc don't run on industry-standard transportation information systems which output GTFS.

Furthermore, FedS is an independent student run organization. I'm in favor of https://fedbus.feds.ca/ having a GTFS / GTFS-realtime system. I am more than happy to connect you to the folks who make that system. Perhaps you can help them output the feed!

I am not prepared to expose something that is user-contributed via the api. We'd want to use a simple very easy to use system that the bus schedulers will use to input the data themselves. This is critical to 
There is an open source solution http://onebusaway.org/ but we haven't gotten around to it and it's not certain we have the resources available to standing it up/maintaining it. I'd love to discuss more. I have office hours on Tuesday between 2:30-4pm in MC2060.

**Closed** 2017-09-06 15:09 UTC
Labels: 2 - Mega Issues, data request
